apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: argocd
  name: argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd
  strategy: {}
  template:
    metadata:
      labels:
        app: argocd
    spec:
      containers:
      - image: alexwhen/docker-2048
        name: argocd
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: "argocd-service"
  labels:
    app: "argocd-service"
spec:
  ports:
  - name: argocd
    port: 80
  selector:
    app: argocd
